{"cells":[{"cell_type":"markdown","metadata":{"id":"elF7EB87aIK8"},"source":["# Exception handling\n","\n","<ul>\n","<li>It is a mechanism in programming to handle runtime errors, which are known as exceptions.&nbsp;</li>\n","<li>It's a process where you define a block of code that will be executed if an error occurs when the program is running. This allows the program to continue running (or terminate gracefully) even if an error occurs.</li>\n","<li>Without exception handling, an error occurring in a program would cause the program to immediately stop. This can be very undesirable, especially in production software, as it can lead to a poor user experience or even data loss.</li>\n","<li>In Python, you use&nbsp;<code><strong>try</strong></code>&nbsp;and&nbsp;<code><strong>except</strong></code>&nbsp;blocks. The&nbsp;<code>try</code>&nbsp;block contains the code that might raise an exception, and the&nbsp;<code><strong>except</strong></code>&nbsp;block contains the code that will be executed if an exception is raised.</li>\n","<li>The <strong>else</strong> block allows you run code without errors.</li>\n","<li>The <strong>finally</strong> block executes code regardless of the try-and-except blocks.</li>\n","</ul>"]},{"cell_type":"markdown","metadata":{"id":"Ispr550waILB"},"source":["<p><strong>Some of the most common types of exceptions are:</strong></p>\n","<ul>\n","<li>\n","<p><strong><code>ZeroDivisionError</code>:</strong> Raised when the second argument of a division or modulo operation is zero.</p>\n","</li>\n","<li>\n","<p><strong><code>TypeError</code>:</strong> Raised when an operation or function is applied to an object of inappropriate type.</p>\n","</li>\n","<li>\n","<p><strong><code>ValueError</code>:</strong> Raised when a built-in operation or function receives an argument that has the right type but an inappropriate value.</p>\n","</li>\n","<li>\n","<p><strong><code>IndexError</code>:</strong> Raised when a sequence subscript is out of range.</p>\n","</li>\n","<li>\n","<p><strong><code>KeyError</code>:</strong> Raised when a dictionary key is not found.</p>\n","</li>\n","<li>\n","<p><strong><code>FileNotFoundError</code>:</strong> Raised when a file or directory is requested but doesn&rsquo;t exist.</p>\n","</li>\n","<li>\n","<p><strong><code>IOError</code>:</strong> Raised when an I/O operation (such as a print statement, the built-in open() function or a method of a file object) fails for an I/O-related reason.</p>\n","</li>\n","<li>\n","<p><strong><code>ImportError</code>:</strong> Raised when an <code>import</code> statement fails to find the module definition or when a <code>from ... import</code> fails to find a name that is to be imported.</p>\n","</li>\n","<li>\n","<p><strong><code>MemoryError</code>:</strong> Raised when an operation runs out of memory.</p>\n","</li>\n","<li>\n","<p><strong><code>OverflowError</code>:</strong> Raised when the result of an arithmetic operation is too large to be expressed by the normal number format.</p>\n","</li>\n","<li>\n","<p><strong><code>AttributeError</code>:</strong> Raised when an attribute reference or assignment fails.</p>\n","</li>\n","<li>\n","<p><strong><code>SyntaxError</code>:</strong> Raised when the parser encounters a syntax error.</p>\n","</li>\n","<li>\n","<p><strong><code>IndentationError</code>:</strong> Raised when there is incorrect indentation.</p>\n","</li>\n","<li>\n","<p><strong><code>NameError</code>:</strong> Raised when a local or global name is not found.</p>\n","</li>\n","</ul>"]},{"cell_type":"markdown","metadata":{"id":"4PpICUWXaILC"},"source":["<p><strong><span style=\"font-family: monospace;\">Role of Try and Except:</span></strong></p>\n","<ul>\n","<li>\n","<p><strong><code>try</code> block:</strong> The code within the <code>try</code> block contains the statements that may potentially raise an exception. It allows you to specify the section of code that you want to monitor for exceptions.</p>\n","</li>\n","<li>\n","<p><strong><code>except</code> block:</strong> If an exception occurs within the <code>try</code> block, the corresponding <code>except</code> block(s) are executed. The <code>except</code> block allows you to define the actions or code that should be executed when a specific exception is raised. You can have multiple <code>except</code> blocks to handle different types of exceptions.</p>\n","</li>\n","<li>The <strong>else</strong> block allows you run code without errors.</li>\n","<li>The <strong>finally</strong> block executes code regardless of the try-and-except blocks.</li>\n","<li> Use the <strong>raise</strong> keyword to throw (or raise) an exception.</li>\n","</ul>"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"l58dK-ljaILD","outputId":"1c8adb3a-bde5-4944-b9d8-44707b866cbc"},"outputs":[{"name":"stdout","output_type":"stream","text":["Some issue with x\n"]}],"source":["# try raise an exception bec x is not defined\n","try:\n","  print(x)\n","except:\n","  print(\"Some issue with x\")"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"R2vK8rkhaILF","outputId":"9a2e983c-c904-4ae6-cafc-73f48f3df0b6"},"outputs":[{"name":"stdout","output_type":"stream","text":["Good morning today is 17th June\n","No issues\n"]}],"source":["\"\"\"You can use the \"else\" keyword to specify a block\n","   of code that will be performed if no errors are raised:\"\"\"\n","try:\n","  print(\"Good morning today is 17th June\")\n","except:\n","  print(\"Some issue\")\n","else:\n","  print(\"No issues\")"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"GJNtMA6JaILG","outputId":"40251048-72df-4e34-ed92-5de10865b033"},"outputs":[{"name":"stdout","output_type":"stream","text":["2\n","The 'try except' executed\n"]}],"source":["\"\"\"If the \"finally\" block is supplied,\n","   it will be executed whether or not the try block raises an error.\"\"\"\n","\n","try:\n","  x = 2\n","  print(x)\n","except:\n","  print(\"There is no X\")\n","finally:\n","  print(\"The 'try except' executed\")\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"8_zWuovKaILH","outputId":"1ece286f-ea40-4a0a-cedf-adddad145689"},"outputs":[{"ename":"Exception","evalue":"There is a problem: X is below zero","output_type":"error","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mException\u001b[0m                                 Traceback (most recent call last)","\u001b[1;32m<ipython-input-17-b914fe32332e>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      4\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      5\u001b[0m \u001b[1;32mif\u001b[0m \u001b[0mx\u001b[0m \u001b[1;33m<\u001b[0m \u001b[1;36m10\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 6\u001b[1;33m   \u001b[1;32mraise\u001b[0m \u001b[0mException\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"There is a problem: X is below zero\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[1;31mException\u001b[0m: There is a problem: X is below zero"]}],"source":["# Use the \"raise\" keyword to throw an exception.\n","\n","x = 2\n","\n","if x < 10:\n","  raise Exception(\"There is a problem: X is below zero\")"]},{"cell_type":"markdown","metadata":{"id":"H6QmV4T4aILH"},"source":["# ZeroDivisionError"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"bqikTQLjaILI","outputId":"52a38784-5c54-441b-8c4c-b66b39ecaf26"},"outputs":[{"name":"stdout","output_type":"stream","text":["Please enter the numerator: 4\n","Please enter the denominator: 0\n"]},{"ename":"ZeroDivisionError","evalue":"division by zero","output_type":"error","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)","\u001b[1;32m<ipython-input-18-cc493999b073>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[0md\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0minput\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"Please enter the denominator: \"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      3\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 4\u001b[1;33m \u001b[0mresult\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mn\u001b[0m \u001b[1;33m/\u001b[0m \u001b[0md\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      5\u001b[0m \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"Result:\"\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mresult\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;31mZeroDivisionError\u001b[0m: division by zero"]}],"source":["n = int(input(\"Please enter the numerator: \"))\n","d = int(input(\"Please enter the denominator: \"))\n","\n","result = n / d\n","print(\"Result:\", result)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"g07HafPjaILJ","outputId":"8dc62072-8732-47e6-bf4b-5bddab133a68"},"outputs":[{"name":"stdout","output_type":"stream","text":["Please enter the numerator: 4\n","Please enter the denominator: 0\n","There is an Error: Division by zero is not allowed.\n"]}],"source":["try:\n","    n = int(input(\"Please enter the numerator: \"))\n","    d = int(input(\"Please enter the denominator: \"))\n","\n","    result = n / d\n","    print(\"Result:\", result)\n","\n","except ZeroDivisionError:\n","    print(\"There is an Error: Division by zero is not allowed.\")\n"]},{"cell_type":"markdown","metadata":{"id":"AAay_pd-aILK"},"source":["# ValueError"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"M4zcqGbtaILK"},"outputs":[],"source":["\"\"\"Raised when a built-in operation or function receives an\n","   argument that has the right type but an inappropriate value.\"\"\"\n","\n","n = int(input(\"Please enter the numerator: \"))\n","d = int(input(\"Please enter the denominator: \"))\n","\n","result = n / d\n","print(\"Result:\", result)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"LsCNJxc8aILK","outputId":"2d7eb7f6-101a-4cb4-9128-f5fddb57faa5"},"outputs":[{"name":"stdout","output_type":"stream","text":["Please enter the numerator: 4/2.56\n","Error: Please enter valid integers for the numerator and denominator.\n"]}],"source":["try:\n","    n = int(input(\"Please enter the numerator: \"))\n","    d = int(input(\"Please enter the denominator: \"))\n","\n","    result = n / d\n","    print(\"Result:\", result)\n","\n","except ValueError:\n","    print(\"Please enter valid integers for the numerator and denominator.\")"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"HOuIMytnaILL","outputId":"94ab3397-87a7-441d-bd0e-d08a9cebcf4b"},"outputs":[{"name":"stdout","output_type":"stream","text":["Please enter the numerator: 2\n","Please enter the denominator: 2\n","Result: 1.0\n"]}],"source":["# Multiple exceptions\n","\n","try:\n","    n = int(input(\"Please enter the numerator: \"))\n","    d = int(input(\"Please enter the denominator: \"))\n","\n","    result = n / d\n","    print(\"Result:\", result)\n","\n","except ValueError:\n","    print(\"Please enter valid integers for the numerator and denominator.\")\n","\n","except ZeroDivisionError:\n","    print(\"Division by zero is not allowed.\")"]},{"cell_type":"markdown","metadata":{"id":"WbzkRUORaILL"},"source":["# TypeError"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"bxoYxv-ZaILM","outputId":"04517ea7-09b2-4023-8aac-2f0f713921c0"},"outputs":[{"name":"stdout","output_type":"stream","text":["Error: TypeError occurred.\n"]}],"source":["try:\n","    x = \"10\"  # Assigning a string value to the variable x\n","    y = 2\n","\n","    z = x + y  # Attempt addition between a string and an integer\n","\n","    print(\"Result:\", z)\n","\n","except TypeError:\n","    print(\"Error: TypeError occurred.\")"]},{"cell_type":"markdown","metadata":{"id":"ri5Mq81DaILM"},"source":["# IndexError"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"N4uQvJmFaILM","outputId":"ec9afcc8-7b25-4462-b1a5-6203479a80e1"},"outputs":[{"name":"stdout","output_type":"stream","text":["IndexError error occurred.\n"]}],"source":["try:\n","    list1 = [1, 2, 3]\n","\n","    print(list1[3])  # Trying to reach an index that is out of range\n","\n","except IndexError:\n","    print(\"IndexError error occurred.\")"]},{"cell_type":"markdown","metadata":{"id":"nMuvwR0uaILN"},"source":["# KeyError"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"gRY4PaUuaILN","outputId":"1cd9987e-e7d9-4d5a-a804-0679e58597f9"},"outputs":[{"name":"stdout","output_type":"stream","text":["KeyError error occurred.\n"]}],"source":["try:\n","    my_dictionary = {\"name\": \"John\", \"age\": 30}\n","\n","    print(my_dictionary[\"city\"])  # Accessing a KEY which does not exist\n","\n","except KeyError:\n","    print(\"KeyError error occurred.\")"]},{"cell_type":"markdown","metadata":{"id":"uPyKigx3aILN"},"source":["# FileNotFoundError"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"DLm2ExCBaILN","outputId":"1ff4b806-77c2-477f-95c0-4c3cc75acc1d"},"outputs":[{"ename":"NameError","evalue":"name 'file_path' is not defined","output_type":"error","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)","\u001b[1;32m<ipython-input-5-dac2ec95e2fe>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      2\u001b[0m     \u001b[0mfile_location\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;34m\"my_file.txt\"\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      3\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 4\u001b[1;33m     \u001b[1;32mwith\u001b[0m \u001b[0mopen\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mfile_path\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m\"r\"\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0mfile\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      5\u001b[0m         \u001b[0mcontents\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mfile\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mread\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      6\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;31mNameError\u001b[0m: name 'file_path' is not defined"]}],"source":["try:\n","    file_location = \"my_file.txt\"\n","\n","    with open(file_path, \"r\") as file:\n","        contents = file.read()\n","\n","except FileNotFoundError:\n","    print(f\"File '{file_path}' not found.\")"]},{"cell_type":"markdown","metadata":{"id":"3pGwgkMNaILO"},"source":["# IOError"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"VqPnYmS6aILO","outputId":"e42ba38c-1e30-425d-f65f-5172a2774994"},"outputs":[{"name":"stdout","output_type":"stream","text":["Unable to write to file 'file123.txt'.\n"]}],"source":["try:\n","    file_location = \"file123.txt\"\n","\n","    with open(file_location, \"w\") as file:\n","        file.write(\"This is my file\")\n","\n","except IOError:\n","    print(f\"Unable to write to file '{file_location}'.\")"]},{"cell_type":"markdown","metadata":{"id":"Sj7RqYqVaILO"},"source":["# ImportError"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"T19nnJh5aILP"},"outputs":[],"source":["try:\n","    import library1234\n","\n","except ImportError:\n","    print(\"Unsuccessful to import module 'library1234'.\")"]},{"cell_type":"markdown","metadata":{"id":"SJUGQTGKaILP"},"source":["# MemoryError"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"ImuqG2GwaILP","outputId":"bee5f07b-b98f-48a8-abb8-c1b963d6ac94"},"outputs":[{"name":"stdout","output_type":"stream","text":["Insufficient memory for the list.\n"]}],"source":["# Creating a large list that consumes a\n","# significant amount of memory\n","try:\n","    large_list = [1] * (10 ** 12)\n","\n","    \"\"\"The phrase [1] * (10 ** 12) generates a\n","    list by repeatedly repeating the element [1].\"\"\"\n","\n","except MemoryError:\n","    print(\"Insufficient memory for the list.\")"]},{"cell_type":"markdown","metadata":{"id":"UFBAjXOraILP"},"source":["# OverflowError"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"ljN6I-twaILP"},"outputs":[],"source":["\"\"\"\"Raised when the result of an arithmetic operation is too large\n","    to be expressed by the normal number format.\"\"\"\"\n","try:\n","    result = 5000 ** 10  # Attempting to calculate an extremely large number\n","\n","except OverflowError:\n","    print(\"Error: Calculation resulted in an overflow.\")\n","else:\n","    print(result)"]},{"cell_type":"markdown","metadata":{"id":"nn79X_XfaILQ"},"source":["# AttributeError"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"zR6TfLczaILQ","outputId":"9b7c8eb8-7063-4941-b8e4-f2a638368fa4"},"outputs":[{"ename":"AttributeError","evalue":"'int' object has no attribute 'append'","output_type":"error","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)","\u001b[1;32m<ipython-input-3-9671491120b2>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      4\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      5\u001b[0m     \u001b[1;31m# Using append method\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 6\u001b[1;33m     \u001b[0mage\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mappend\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;36m12\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      7\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      8\u001b[0m \u001b[1;32mexcept\u001b[0m \u001b[0mOverflowError\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;31mAttributeError\u001b[0m: 'int' object has no attribute 'append'"]}],"source":["try:\n","\n","    age = 20\n","\n","    # Using append method\n","    age.append(12)\n","\n","except OverflowError:\n","    print(\"'age' object has no attribute.\")\n","else:\n","    print(result)"]},{"cell_type":"markdown","metadata":{"id":"dGp1thQraILQ"},"source":["# SyntaxError"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"_0PHMoWtaILR","outputId":"4468b776-d46d-4eae-c1d8-cde1ea49a8a5"},"outputs":[{"ename":"SyntaxError","evalue":"invalid syntax (<ipython-input-4-fa05a04e9107>, line 3)","output_type":"error","traceback":["\u001b[1;36m  File \u001b[1;32m\"<ipython-input-4-fa05a04e9107>\"\u001b[1;36m, line \u001b[1;32m3\u001b[0m\n\u001b[1;33m    age = 20\u001b[0m\n\u001b[1;37m    ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m invalid syntax\n"]}],"source":["try:\n","    print(\"John age is:\"\n","    age = 20\n","\n","except SyntaxError:\n","    print(\"Error: Invalid syntax.\")"]},{"cell_type":"markdown","metadata":{"id":"hA6UBujGaILR"},"source":["# IndentationError"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"gekZZ5JKaILR","outputId":"e1efbc49-f081-48be-b76f-8fc706a28789"},"outputs":[{"ename":"IndentationError","evalue":"unexpected indent (<ipython-input-5-713cecd987b1>, line 3)","output_type":"error","traceback":["\u001b[1;36m  File \u001b[1;32m\"<ipython-input-5-713cecd987b1>\"\u001b[1;36m, line \u001b[1;32m3\u001b[0m\n\u001b[1;33m    age = 50\u001b[0m\n\u001b[1;37m    ^\u001b[0m\n\u001b[1;31mIndentationError\u001b[0m\u001b[1;31m:\u001b[0m unexpected indent\n"]}],"source":["try:\n","    name = \"John\"\n","        age = 50\n","\n","except IndentationError:\n","    print(\"There is an IndentationError\")"]},{"cell_type":"markdown","metadata":{"id":"aGJvrV8yaILS"},"source":["# NameError"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"1EqEVXdzaILS","outputId":"d961ad7f-a185-4b5b-d930-d50623d512af"},"outputs":[{"name":"stdout","output_type":"stream","text":["NameError is there\n"]}],"source":["try:\n","    side = \"4\"\n","    print(area)  # Attempting to access an undefined variable\n","\n","except NameError:\n","    print(\"NameError is there\")"]},{"cell_type":"markdown","metadata":{"id":"03XPZcHjaILc"},"source":["<p><strong>Here's a brief description of each exception:</strong></p>\n","<ol>\n","<li><strong><code>BaseException</code>:</strong> The base class for all built-in exceptions.</li>\n","<li><strong><code>Exception</code>:</strong> The base class for all non-exit exceptions.</li>\n","<li><strong><code>ArithmeticError</code>:</strong> Raised for any arithmetic errors.</li>\n","<li><strong><code>BufferError</code>:</strong> Raised when operations on a buffer are not possible.</li>\n","<li><strong><code>LookupError</code>:</strong> Raised when a mapping (dictionary) key or sequence index is not found.</li>\n","<li><strong><code>AssertionError</code>:</strong> Raised when an <code>assert</code> statement fails.</li>\n","<li><strong><code>AttributeError</code>:</strong> Raised when attribute reference or assignment fails.</li>\n","<li><strong><code>EOFError</code>:</strong> Raised when the <code>input()</code> function hits an end-of-file condition (EOF).</li>\n","<li><strong><code>FloatingPointError</code>:</strong> Raised when a floating point operation fails.</li>\n","<li><strong><code>GeneratorExit</code>:</strong> Raised when a generator or coroutine is closed.</li>\n","<li><strong><code>ImportError</code>:</strong> Raised when the <code>import</code> statement fails to find the module definition.</li>\n","<li><strong><code>ModuleNotFoundError</code>:</strong> A subclass of <code>ImportError</code>, raised when an <code>import</code> statement fails to find the module.</li>\n","<li><strong><code>IndexError</code>:</strong> Raised when a sequence subscript (index) is out of range.</li>\n","<li><strong><code>KeyError</code>:</strong> Raised when a dictionary key is not found.</li>\n","<li><strong><code>KeyboardInterrupt</code>:</strong> Raised when the user interrupts program execution (usually by pressing Ctrl+C).</li>\n","<li><strong><code>MemoryError</code>:</strong> Raised when an operation runs out of memory.</li>\n","<li><strong><code>NameError</code>:</strong> Raised when a local or global name is not found.</li>\n","<li><strong><code>NotImplementedError</code>:</strong> Raised when an abstract method requiring an override in an inherited class is not provided.</li>\n","<li><strong><code>OSError</code>:</strong> Raised when a system-related error occurs.</li>\n","<li><strong><code>OverflowError</code>:</strong> Raised when the result of an arithmetic operation is too large to be expressed.</li>\n","<li><strong><code>RecursionError</code>:</strong> Raised when the maximum recursion depth has been exceeded.</li>\n","<li><strong><code>ReferenceError</code>:</strong> Raised when a weak reference proxy is used to access a garbage collected referent.</li>\n","<li><strong><code>RuntimeError</code>:</strong> Raised when an error is detected that doesn&rsquo;t fall in any of the other categories.</li>\n","<li><strong><code>StopIteration</code>:</strong> Raised by built-in function <code>next()</code> and an iterator&lsquo;s <code>__next__()</code> method to signal that there are no further items.</li>\n","<li><strong><code>StopAsyncIteration</code>:</strong> Raised by an asynchronous iterator object&rsquo;s <code>__anext__()</code> method to stop the iteration.</li>\n","<li><strong><code>SyntaxError</code>:</strong> Raised by the parser when a syntax error is encountered.</li>\n","<li><strong><code>IndentationError</code>:</strong> Raised when there is incorrect indentation.</li>\n","<li><strong><code>TabError</code>:</strong> Raised when indentation contains mixed tabs and spaces.</li>\n","<li><strong><code>SystemError</code>:</strong> Raised when the interpreter finds an internal problem.</li>\n","<li><strong><code>SystemExit</code>:</strong> Raised by the <code>sys.exit()</code> function.</li>\n","<li><strong><code>TypeError</code>:</strong> Raised when an operation or function is applied to an object of inappropriate type.</li>\n","<li><strong><code>UnboundLocalError</code>:</strong> Raised when a local variable is referenced before it has been assigned a value.</li>\n","<li><strong><code>UnicodeError</code>:</strong> Raised when a Unicode-related encoding or decoding error occurs.</li>\n","<li><strong><code>UnicodeEncodeError</code>:</strong> Raised when a Unicode-related error occurs during encoding.</li>\n","<li><strong><code>UnicodeDecodeError</code>:</strong> Raised when a Unicode-related error occurs during decoding.</li>\n","<li><strong><code>UnicodeTranslateError</code>:</strong> Raised when a Unicode-related error occurs during translating.</li>\n","<li><strong><code>ValueError</code>:</strong> Raised when a built-in operation or function receives an argument that has the right type but an inappropriate value.</li>\n","<li><strong><code>ZeroDivisionError</code>:</strong> Raised when the second argument of a division or modulo operation is zero.</li>\n","<li><strong><code>EnvironmentError</code>:</strong> Base class for exceptions that can occur outside the Python system.</li>\n","<li><strong><code>IOError</code>:</strong> Raised when an I/O operation (such as a print statement, the built-in open() function or a method of a file object)</li>\n","</ol>"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"mVmB-MdSaILc"},"outputs":[],"source":[]},{"cell_type":"code","execution_count":null,"metadata":{"id":"C15V0XQqaILc"},"outputs":[],"source":["def quiz_on_exception():\n","    # Quiz Questions\n","    quiz_data = [\n","        {\n","            \"question\": \"Which keyword is used for exception handling?\",\n","            \"options\": ['a) raise', 'b) try', 'c) handle', 'd) exception'],\n","            \"answer\": 'b'\n","        },\n","        {\n","            \"question\": \"What is the purpose of the 'finally' clause in Python exception handling?\",\n","            \"options\": ['a) It executes no matter what', 'b) It is executed if an exception occurs', 'c) It is executed if no exception', 'd) None of the above'],\n","            \"answer\": 'a'\n","        },\n","        {\n","            \"question\": \"Which built-in exception is raised when a function or operation is not implemented yet?\",\n","            \"options\": ['a) NotImplementedError', 'b) ArithmeticError', 'c) BufferError', 'd) AssertionError'],\n","            \"answer\": 'a'\n","        },\n","        {\n","            \"question\": \"Which of the following exceptions is NOT raised by Python built-in operations?\",\n","            \"options\": ['a) IOError', 'b) FileNotFoundError', 'c) KeyNotFoundError', 'd) ZeroDivisionError'],\n","            \"answer\": 'c'\n","        },\n","        {\n","            \"question\": \"What exception is raised when a local or global name is not found?\",\n","            \"options\": ['a) AttributeError', 'b) KeyError', 'c) ImportError', 'd) NameError'],\n","            \"answer\": 'd'\n","        },\n","        {\n","            \"question\": \"What exception is raised when the parser encounters a syntax error?\",\n","            \"options\": ['a) AttributeError', 'b) SyntaxError', 'c) IndentationError', 'd) ValueError'],\n","            \"answer\": 'b'\n","        },\n","        {\n","            \"question\": \"What exception is raised when there is incorrect indentation?\",\n","            \"options\": ['a) IndentationError', 'b) ValueError', 'c) SyntaxError', 'd) TypeError'],\n","            \"answer\": 'a'\n","        },\n","        {\n","            \"question\": \"What exception is raised when an operation or function receives an argument of the right type but an inappropriate value?\",\n","            \"options\": ['a) ValueError', 'b) TypeError', 'c) IndexError', 'd) KeyError'],\n","            \"answer\": 'a'\n","        },\n","        {\n","            \"question\": \"What exception is raised when a sequence subscript is out of range?\",\n","            \"options\": ['a) KeyError', 'b) ValueError', 'c) TypeError', 'd) IndexError'],\n","            \"answer\": 'd'\n","        },\n","        {\n","            \"question\": \"What exception is raised when an import statement fails to find the module definition or when a from ... import fails to find a name that is to be imported?\",\n","            \"options\": ['a) ImportError', 'b) ValueError', 'c) FileNotFoundError', 'd) AttributeError'],\n","            \"answer\": 'a'\n","        },\n","        {\n","            \"question\": \"What exception is raised when an operation runs out of memory?\",\n","            \"options\": ['a) MemoryError', 'b) BufferError', 'c) OverflowError', 'd) ArithmeticError'],\n","            \"answer\": 'a'\n","        },\n","        {\n","            \"question\": \"What exception is raised when the result of an arithmetic operation is too large to be expressed by the normal number format?\",\n","            \"options\": ['a) OverflowError', 'b) MemoryError', 'c) IndexError', 'd) ArithmeticError'],\n","            \"answer\": 'a'\n","        },\n","        {\n","            \"question\": \"What exception is raised when an attribute reference or assignment fails?\",\n","            \"options\": ['a) AttributeError', 'b) KeyError', 'c) ImportError', 'd) NameError'],\n","            \"answer\": 'a'\n","        },\n","        {\n","            \"question\": \"What exception is raised when a file or directory is requested but doesn’t exist?\",\n","            \"options\": ['a) FileNotFoundError', 'b) IOError', 'c) ImportError', 'd) KeyError'],\n","            \"answer\": 'a'\n","        },\n","        {\n","            \"question\": \"What exception is raised when a dictionary key is not found?\",\n","            \"options\": ['a) KeyError', 'b) ValueError', 'c) IndexError', 'd) FileNotFoundError'],\n","            \"answer\": 'a'\n","        },\n","    ]\n","\n","    def ask_question(question_data):\n","        print(question_data[\"question\"])\n","        for option in question_data[\"options\"]:\n","            print(option)\n","        while True:\n","            try:\n","                user_answer = input(\"Enter your answer: \")\n","                if user_answer in ['a', 'b', 'c', 'd']:\n","                    correct = user_answer == question_data[\"answer\"]\n","                    if not correct:\n","                        print(f\"Incorrect.\")\n","                    return user_answer, question_data[\"answer\"], correct\n","                else:\n","                    raise ValueError(\"Invalid option. Please enter a, b, c, or d.\")\n","            except ValueError as e:\n","                print(e)\n","\n","    score = 0\n","    all_answers = []  # a list to store all the user's answers and correct answers\n","\n","    for question_data in quiz_data:\n","        user_answer, correct_answer, correct = ask_question(question_data)\n","        all_answers.append((question_data[\"question\"], user_answer, correct_answer, correct))\n","        if correct:\n","            print(\"Correct!\")\n","            score += 1\n","\n","    print(\"\\n\"+\"-\"*30+\"\\nQuiz Results\\n\"+\"-\"*30)\n","    for item in all_answers:\n","        print(f\"Question: {item[0]}\\nYour Answer: {item[1]}\\nCorrect Answer: {item[2]}\\n{'Correct' if item[3] else 'Incorrect'}\")\n","        print(\"-\"*30)\n","    print(f\"You scored {score}/{len(quiz_data)}.\")\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"uqSmTRzUaILd"},"outputs":[],"source":["a\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"rGr0EUyXaILd","outputId":"3b7581b0-ea90-4c25-85cd-236caeed4e75"},"outputs":[{"name":"stdout","output_type":"stream","text":["Which keyword is used for exception handling?\n","a) raise\n","b) try\n","c) handle\n","d) exception\n","Enter your answer: a\n","Incorrect.\n","What is the purpose of the 'finally' clause in Python exception handling?\n","a) It executes no matter what\n","b) It is executed if an exception occurs\n","c) It is executed if no exception\n","d) None of the above\n","Enter your answer: a\n","Correct!\n","Which built-in exception is raised when a function or operation is not implemented yet?\n","a) NotImplementedError\n","b) ArithmeticError\n","c) BufferError\n","d) AssertionError\n","Enter your answer: a\n","Correct!\n","Which of the following exceptions is NOT raised by Python built-in operations?\n","a) IOError\n","b) FileNotFoundError\n","c) KeyNotFoundError\n","d) ZeroDivisionError\n","Enter your answer: a\n","Incorrect.\n","What exception is raised when a local or global name is not found?\n","a) AttributeError\n","b) KeyError\n","c) ImportError\n","d) NameError\n","Enter your answer: a\n","Incorrect.\n","What exception is raised when the parser encounters a syntax error?\n","a) AttributeError\n","b) SyntaxError\n","c) IndentationError\n","d) ValueError\n","Enter your answer: a\n","Incorrect.\n","What exception is raised when there is incorrect indentation?\n","a) IndentationError\n","b) ValueError\n","c) SyntaxError\n","d) TypeError\n","Enter your answer: a\n","Correct!\n","What exception is raised when an operation or function receives an argument of the right type but an inappropriate value?\n","a) ValueError\n","b) TypeError\n","c) IndexError\n","d) KeyError\n","Enter your answer: a\n","Correct!\n","What exception is raised when a sequence subscript is out of range?\n","a) KeyError\n","b) ValueError\n","c) TypeError\n","d) IndexError\n","Enter your answer: a\n","Incorrect.\n","What exception is raised when an import statement fails to find the module definition or when a from ... import fails to find a name that is to be imported?\n","a) ImportError\n","b) ValueError\n","c) FileNotFoundError\n","d) AttributeError\n","Enter your answer: a\n","Correct!\n","What exception is raised when an operation runs out of memory?\n","a) MemoryError\n","b) BufferError\n","c) OverflowError\n","d) ArithmeticError\n","Enter your answer: a\n","Correct!\n","What exception is raised when the result of an arithmetic operation is too large to be expressed by the normal number format?\n","a) OverflowError\n","b) MemoryError\n","c) IndexError\n","d) ArithmeticError\n","Enter your answer: a\n","Correct!\n","What exception is raised when an attribute reference or assignment fails?\n","a) AttributeError\n","b) KeyError\n","c) ImportError\n","d) NameError\n","Enter your answer: a\n","Correct!\n","What exception is raised when a file or directory is requested but doesn’t exist?\n","a) FileNotFoundError\n","b) IOError\n","c) ImportError\n","d) KeyError\n","Enter your answer: a\n","Correct!\n","What exception is raised when a dictionary key is not found?\n","a) KeyError\n","b) ValueError\n","c) IndexError\n","d) FileNotFoundError\n","Enter your answer: a\n","Correct!\n","\n","------------------------------\n","Quiz Results\n","------------------------------\n","Question: Which keyword is used for exception handling?\n","Your Answer: a\n","Correct Answer: b\n","Incorrect\n","------------------------------\n","Question: What is the purpose of the 'finally' clause in Python exception handling?\n","Your Answer: a\n","Correct Answer: a\n","Correct\n","------------------------------\n","Question: Which built-in exception is raised when a function or operation is not implemented yet?\n","Your Answer: a\n","Correct Answer: a\n","Correct\n","------------------------------\n","Question: Which of the following exceptions is NOT raised by Python built-in operations?\n","Your Answer: a\n","Correct Answer: c\n","Incorrect\n","------------------------------\n","Question: What exception is raised when a local or global name is not found?\n","Your Answer: a\n","Correct Answer: d\n","Incorrect\n","------------------------------\n","Question: What exception is raised when the parser encounters a syntax error?\n","Your Answer: a\n","Correct Answer: b\n","Incorrect\n","------------------------------\n","Question: What exception is raised when there is incorrect indentation?\n","Your Answer: a\n","Correct Answer: a\n","Correct\n","------------------------------\n","Question: What exception is raised when an operation or function receives an argument of the right type but an inappropriate value?\n","Your Answer: a\n","Correct Answer: a\n","Correct\n","------------------------------\n","Question: What exception is raised when a sequence subscript is out of range?\n","Your Answer: a\n","Correct Answer: d\n","Incorrect\n","------------------------------\n","Question: What exception is raised when an import statement fails to find the module definition or when a from ... import fails to find a name that is to be imported?\n","Your Answer: a\n","Correct Answer: a\n","Correct\n","------------------------------\n","Question: What exception is raised when an operation runs out of memory?\n","Your Answer: a\n","Correct Answer: a\n","Correct\n","------------------------------\n","Question: What exception is raised when the result of an arithmetic operation is too large to be expressed by the normal number format?\n","Your Answer: a\n","Correct Answer: a\n","Correct\n","------------------------------\n","Question: What exception is raised when an attribute reference or assignment fails?\n","Your Answer: a\n","Correct Answer: a\n","Correct\n","------------------------------\n","Question: What exception is raised when a file or directory is requested but doesn’t exist?\n","Your Answer: a\n","Correct Answer: a\n","Correct\n","------------------------------\n","Question: What exception is raised when a dictionary key is not found?\n","Your Answer: a\n","Correct Answer: a\n","Correct\n","------------------------------\n","You scored 10/15.\n"]}],"source":["quiz_on_exception()"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"kRVR8MrZaILd"},"outputs":[],"source":[]},{"cell_type":"code","execution_count":null,"metadata":{"id":"C4SW7r3MaILe"},"outputs":[],"source":[]},{"cell_type":"code","execution_count":null,"metadata":{"id":"Fqx8qI1SaILe"},"outputs":[],"source":[]}],"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.5"},"colab":{"provenance":[]}},"nbformat":4,"nbformat_minor":0}